### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by tarmiziAdam2005** [bodono/AA#1]
Hello, I am interested in this Anderson acceleration code. However, is this code referring to any articles or notes ? Can you point out any articles related to this code ? It would be helpful for me to further study the topic and code. Thank you.

**Comment by bodono** [comment]
It's a companion to our paper here: 

https://web.stanford.edu/~boyd/papers/nonexp_global_aa1.html

I will update the README with a link to this.

**Comment by bodono** [comment]
The main repo is actually here: https://github.com/cvxgrp/aa
